<?
    /***********************************************************************
     * constants.inc
     * 
     * Adapted from:
     * Computer Science 50
     *
     * Global constants.
     **********************************************************************/


    // name of your database
    define("DB", "mcginn");

    // username for your database
    define("DBUSER", "mcginn");

    // password for your database
    define("DBPASS", "EHyzuJG");

    // fully-qualified domain name and port of database server
    define("DBSERVER","cs50-1.seas.harvard.edu");

?>
