/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountDialog.java
 *
 * Created on Jul 19, 2009, 6:35:07 PM
 */
package org.lsm.finances.v2.swing;

import java.awt.Component;
import java.awt.Frame;
import java.util.LinkedHashMap;
import java.util.Map;
import org.lsm.finances.v2.object.Account;
import org.lsm.finances.v2.object.FinanceProfile;

/**
 *
 * @author Loren
 */
public class AccountDialog extends AddDialog<Account> {

    public AccountDialog(Frame parent, FinanceProfile profile) {
        super(parent, profile);
        initComponents();
    }

    @Override
    protected Account getNew() {
        boolean inputInvalid = false;
        Map<Component, Boolean> isInvalidMap = new LinkedHashMap<Component, Boolean>();

        String name = textName.getText();
        if (name == null || name.equals("")) {
            isInvalidMap.put(labelName, true);
            inputInvalid = true;
        } else {
            isInvalidMap.put(labelName, false);
        }

        String desc = textDesc.getText();
        if (desc == null || desc.equals("")) {
            isInvalidMap.put(labelDesc, true);
            inputInvalid = true;
        } else {
            isInvalidMap.put(labelDesc, false);
        }

        highlightErrors(isInvalidMap);
        if (inputInvalid) {
            throw new IllegalArgumentException();
        }

        return new Account(profile.getNewAccountId(), name, desc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        labelDesc = new javax.swing.JLabel();
        textDesc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account");

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonAdd);

        buttonCancel.setText("Close");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonCancel);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        inputPanel.setLayout(new java.awt.GridBagLayout());

        labelName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(labelName, gridBagConstraints);

        textName.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(textName, gridBagConstraints);

        labelDesc.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(labelDesc, gridBagConstraints);

        textDesc.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        inputPanel.add(textDesc, gridBagConstraints);

        getContentPane().add(inputPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        try {
            profile.addAccount(getNew());
            textDesc.setText("");
            textName.setText("");
        } catch (IllegalArgumentException e) {
        }
}//GEN-LAST:event_buttonAddActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        close();
    }//GEN-LAST:event_buttonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JLabel labelName;
    private javax.swing.JTextField textDesc;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
