/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountDialog.java
 *
 * Created on Jul 19, 2009, 6:35:07 PM
 */
package org.lsm.finances.v2.swing;

import java.awt.Frame;
import org.lsm.finances.v2.object.Category;
import org.lsm.finances.v2.object.FinanceProfile;
import org.lsm.finances.v2.swing.model.CategoryListModel;
import org.lsm.finances.v2.swing.model.Renderers;

/**
 *
 * @author Loren
 */
public class CatDialog extends AddDialog<Category> {

    public CatDialog(Frame parent, FinanceProfile profile) {
        super(parent, profile);
        initComponents();
    }

    @Override
    protected Category getNew() {
        if (textCategory.getText() == null || textCategory.getText().equals("")) {
            throw new IllegalArgumentException();
        }
        return new Category(textCategory.getText(), profile.getNewCatId());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        comboCategory = new javax.swing.JComboBox();
        labelCategory = new javax.swing.JLabel();
        textCategory = new javax.swing.JTextField();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account");
        setResizable(false);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add(evt);
            }
        });
        buttonPanel.add(buttonAdd);

        buttonCancel.setText("Close");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonCancel);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        inputPanel.setLayout(new java.awt.GridBagLayout());

        comboCategory.setModel(new CategoryListModel(profile));
        comboCategory.setPreferredSize(new java.awt.Dimension(120, 20));
        comboCategory.setRenderer(new Renderers.CatListRenderer());
        inputPanel.add(comboCategory, new java.awt.GridBagConstraints());

        labelCategory.setText("Add Category:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        inputPanel.add(labelCategory, gridBagConstraints);

        textCategory.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        inputPanel.add(textCategory, gridBagConstraints);

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletedeleteCat(evt);
            }
        });
        inputPanel.add(buttonDelete, new java.awt.GridBagConstraints());

        getContentPane().add(inputPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeletedeleteCat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletedeleteCat
        profile.removeCategory((Category) comboCategory.getSelectedItem());
        comboCategory.setSelectedItem(null);
}//GEN-LAST:event_buttonDeletedeleteCat

    private void add(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add
        try {
            profile.addCategory(getNew());
            textCategory.setText("");
        } catch (IllegalArgumentException e) {
        }
    }//GEN-LAST:event_add

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        close();
    }//GEN-LAST:event_buttonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox comboCategory;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JTextField textCategory;
    // End of variables declaration//GEN-END:variables
}
